### ISSUE TITLE
Duplicate code in feature

### ISSUE THREAD

**Issue by bilginyuksel** [ro-ll-bot/RLB_CORE_LOGO_SI_Mobile#1]
I believe if we write every screen's component in screen's folder seperate than others. It will force us to write duplicate codes. Instead of using this way we can generalize the parts (components) in folder components. Then every screen can use these components.

### Recommended project structure

``` 
                                  _________ first_component.dart
view______________ components____|_________second_component.dart
             |
             |_________ screens________ first_screen.dart
                                   |___ second_screen.dart
```

**Comment by HasancanKazan** [comment]
Thank you yuksel for your suggestion. Once the folder is made, we can apply it this way.
